name: Create ranekd map data
on:
  schedule:
    - cron: "0 11 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/get-ranked-maps
        with:
          output_json_path: "./rankedmaps.json"
      - name: Release
        run: |
          set -x
          zip rankedmaps.zip rankedmaps.json
          assets=()
          assets+=(""rankedmaps.zip")
          tag_name=`date '+%Y%m%d%H%M'`
          gh release create "$tag_name" "${assets[@]}" -t "Latest"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Cleanup
        uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 1
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}